# Generated by Django 2.1 on 2018-08-22 06:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('title_original', models.CharField(blank=True, max_length=50)),
                ('director', models.CharField(max_length=20)),
                ('cast', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('length', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=datetime.date(1, 1, 1))),
                ('review_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date(1, 1, 1))),
                ('author', models.CharField(blank=True, max_length=30)),
                ('title', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(db_index=True, default=-1)),
                ('content', models.TextField(blank=True, default='')),
                ('cos_sim', models.FloatField(blank=True, null=True)),
                ('jac_sim', models.FloatField(blank=True, null=True)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='reviews.Review')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cluster_id', models.IntegerField(default=-1)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='reviews.Movie')),
            ],
        ),
    ]
