# Generated by Django 2.1 on 2018-08-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='label',
            new_name='cluster_id',
        ),
        migrations.AddField(
            model_name='sentence',
            name='review_position',
            field=models.IntegerField(null=True),
        ),
    ]
